### ISSUE TITLE
Small errors in schematics.

### ISSUE THREAD

**Issue by stefaweb** [tvicol/Q17-a-QUAD405-audiophile-approach#1]
Hi Tiby!

Nice projet.

Where is the true. Only one 2200uF or two?

Sincerely,

![q17_sch_error_1](https://user-images.githubusercontent.com/12907102/140755442-f84ee64b-7c5e-4e30-9912-47ec71c2b342.jpg)

![q17_sch_error_12 pg](https://user-images.githubusercontent.com/12907102/140755462-e4f35e89-4fe4-40ae-82d0-323b3b100d64.png)

**Comment by tvicol** [comment]
Thank you !

It is only one, PCB was designed to accommodate same electrolytic in two dimensions.
