### ISSUE TITLE
KICAD Library for Q17

### ISSUE THREAD

**Issue by stefaweb** [tvicol/Q17-a-QUAD405-audiophile-approach#2]
Hello Tibi,

If you agree, could you create a directory called "KICAD Library" in KiCad source to store library files as in my example? And after move "L.kicad_mod" and "L_new.kicad_mod" inside footprints.pretty.

As I'm using more and more dedicated footprints and 3D models, it will be easier for me to manage all this in my fork when I pull the files from your project.

A better name for the L1 inductor will be easier to understand (as L_Q17_pcb.kicad_mod) too.

Regards,

Stef.

In KiCad source:
.
├── KICAD\ Library
│   ├── 3dmodels
│   │   ├── 744711005_Download_STP_744711005_rev1.stp
│   │   ├── c-63849-1-g-3d.stp
│   │   └── mica-cap.step
│   └── footprints.pretty
│       ├── C_Mica_L11.4mm_W4.3mm_H9.1_P5.9mm.kicad_mod
│       ├── C_Rect_C7_Q17-Mini.kicad_mod
│       └── Faston_connector.kicad_mod
├── L.kicad_mod
├── L_new.kicad_mod

**Comment by tvicol** [comment]
Done !

**Comment by stefaweb** [comment]
Thanks fine.

On more. ;)

Q17.pdf file would be better with a more explicit filename.

Stef.

**Comment by tvicol** [comment]
Done & thx !
