### ISSUE TITLE
KICAD -> 6.0

### ISSUE THREAD

**Issue by stefaweb** [tvicol/Q17-a-QUAD405-audiophile-approach#3]
`Use KiCad 5.99 or later to open and edit source files. KiCad 5.99 can be downloaded from CERN, for windows, for MacBook`

Stef.

**Comment by tvicol** [comment]
Please be more explicit in your request.

**Comment by stefaweb** [comment]
Sorry Tibi.

KICAD is version 6.0 in https://kicad-downloads.s3.cern.ch/index.html?prefix=osx/nightly/.

![sc](https://user-images.githubusercontent.com/12907102/142851348-372d388d-5301-475c-a1cf-ae15de141d9f.jpg)

**Comment by tvicol** [comment]
Yes, KiCad 6.0-rc1 was released and is available in nighty. This use same file format as 5.99 and there should be no issues. If you have any, please let me know.
As I'm using an old macbook, I need to compile the release and this take some time.

**Comment by stefaweb** [comment]
Here with an old Intel iMac from 2015 it works quite well in 6.0. Some crashes from time to time when quitting the Kicad software and in 3D mode if 3D footprints are not present. I also found a bug that changes the PAD from round to oval when editing several PAD in a row.
