### ISSUE TITLE
Q17-Mini available

### ISSUE THREAD

**Issue by stefaweb** [tvicol/Q17-a-QUAD405-audiophile-approach#5]
Hi Tiby,

As diyaudio.com his closed. Just to say that the board is working fine (and tested with the scope). I solved the problem. The Q12 BD139 was mounted upside down. I corrected this in the first production PCB 1.1 published on my Github repository.

Cheers,

Stéphane

**Comment by tvicol** [comment]
Hi Stéphane,

Thank you very much for your feedback, much appreciated !

Regards,
Tibi
